üîç Loading model for hydro from hydro.h5
üîç Loading model for load from load.h5
üîç Loading model for price from price.h5
üîç Loading model for solar from solar.h5
üîç Loading model for wind from wind.h5
C:\Users\gepap\Anaconda3\Lib\site-packages\gymnasium\spaces\box.py:235: UserWarning: [33mWARN: Box low's precision lowered by casting to float32, current low.dtype=float64[0m
  gym.logger.warn(
C:\Users\gepap\Anaconda3\Lib\site-packages\gymnasium\spaces\box.py:305: UserWarning: [33mWARN: Box high's precision lowered by casting to float32, current high.dtype=float64[0m
  gym.logger.warn(
Traceback (most recent call last):
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'price'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gepap\Desktop\Thesis\RL Agent\main.py", line 64, in <module>
    main()
  File "C:\Users\gepap\Desktop\Thesis\RL Agent\main.py", line 47, in main
    check_env(env)
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\stable_baselines3\common\env_checker.py", line 482, in check_env
    _check_returned_values(env, observation_space, action_space)
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\stable_baselines3\common\env_checker.py", line 313, in _check_returned_values
    data = env.step(action)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Desktop\Thesis\RL Agent\forecast_wrapper_env.py", line 26, in step
    obs, reward, done, truncated, info = self.env.step(action)
                                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Desktop\Thesis\RL Agent\RenewableInvestmentEnv.py", line 85, in step
    price = row['price']
                   ~~~^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gepap\Anaconda3\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'price'
